### ISSUE TITLE
Page reload back to back after complete registration

### ISSUE THREAD

**Issue by Starboy-Sharma** [joshcawthorne/work-from#3]
I am using Firefox in Ubuntu. I open the web in private window and complete the registration and fill all the on-boarding details as well. Then it takes me to the dashboard page. But after some times my page is reload back to back. 
I am also adding a one more issue
Validation Issue in Full Name 
- If user enter his first name and give a space then it is allowing me to proceed
- You can also give space before your first name and it is allowing me to proceed

![Screenshot from 2021-08-11 12-06-34](https://user-images.githubusercontent.com/31812684/128981587-f7694ecc-0d27-407a-b16d-40001dfcbf3d.png)

**Comment by florian-lefebvre** [comment]
I'm on Firefox on Windows and I also get the infinite reload bug

**Comment by joshcawthorne** [comment]
I think this was caused due to default rest days not being applied to newly created companies. Should be resolved now :)

**Comment by florian-lefebvre** [comment]
I cleaned the local storage, logged in again and I still get the issue @joshcawthorne. Maybe it will take some time to apply your changes ?

**Comment by joshcawthorne** [comment]
@florian-lefebvre it should be sorted. Would you be able to try again now? If not, let me know what email you use and maybe I'll need to reset your profile... I think the issue is being caused by not all required data being inputted on onboarding :D

**Comment by florian-lefebvre** [comment]
Still not working, I'll sending my mail adress to your email shown on your Github profile.

**Comment by joshcawthorne** [comment]
Thanks!

**Comment by florian-lefebvre** [comment]
It worked 👍
